import { STATS, STAT_DEFS, aggregate, activeEvents, eventLabel, formatGame, lineup, localDate, percent } from './domain.js';

export const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
const paths = {
  ball: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3v18M5.6 5.6c7 3 7 9.8 0 12.8M18.4 5.6c-7 3-7 9.8 0 12.8"/>',
  home: '<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',
  team: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/>',
  history: '<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8M8 12h8M8 16h5"/>',
  settings: '<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="9" cy="18" r="2"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
  back: '<path d="m14 6-6 6 6 6"/>',
  close: '<path d="m6 6 12 12M6 18 18 6"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  undo: '<path d="m8 4-5 5 5 5M3 9h11a6 6 0 0 1 0 12h-3"/>',
  sub: '<path d="M3 7h17m-4-4 4 4-4 4M21 17H4m4-4-4 4 4 4"/>',
  download: '<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
  share: '<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.7 10.6 6.6-4.1M8.7 13.4l6.6 4.1"/>',
  shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM8 12l3 3 5-6"/>',
  chevron: '<path d="m9 6 6 6-6 6"/>',
  more: '<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
  trash: '<path d="M4 7h16M10 11v6M14 11v6M9 7V4h6v3M6 7l1 14h10l1-14"/>',
};
export const icon = (name, cls = '') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.ball}</svg>`;
const action = (name, text, cls = 'button secondary', attrs = '') => `<button class="${cls}" data-action="${name}" ${attrs}>${text}</button>`;
const tag = text => `<span class="tag">${esc(text)}</span>`;
const statusChip = s => `<span class="connection ${s.pwa.ready ? 'ready' : ''}"><i></i>${s.pwa.ready ? (navigator.onLine ? 'オフライン利用OK' : 'オフライン') : s.pwa.error ? 'キャッシュ未完了' : 'オフライン準備中'}</span>`;
function nav(current) {
  return `<nav class="navigation" aria-label="メインナビゲーション">${[['home', 'ホーム'], ['teams', 'チーム'], ['history', '履歴'], ['settings', '設定']].map(([id, label]) => `<a href="#${id}" class="nav-item ${current === id ? 'selected' : ''}" ${current === id ? 'aria-current="page"' : ''}>${icon(id === 'teams' ? 'team' : id)}<span>${label}</span></a>`).join('')}</nav>`;
}
export function shell(state, content) {
  return `<div class="app-shell"><aside class="sidebar"><a class="brand" href="#home">${icon('ball')}<span>COURTSIDE<small>BASKETBALL STATS</small></span></a>${nav(state.page)}<div class="sidebar-note">WATCH THE GAME.<br>CAPTURE THE MOMENT.<span>すべての記録を、この端末に。</span></div></aside><div class="main-column"><header class="app-header"><a href="#home" class="mobile-brand">${icon('ball')}<strong>COURTSIDE</strong></a>${statusChip(state)}</header><main class="page" id="main">${content}</main></div></div>`;
}
const heading = (eyebrow, title, right = '') => `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div>${right}</div>`;
function gameCard(g, events, resume = false, deletable = false) {
  const a = aggregate(g, events.filter(e => e.gameId === g.id));
  const card = `<a class="game-card" href="#${resume ? 'live' : 'box'}/${g.id}"><div class="game-meta"><span>${esc(g.date.replaceAll('-', '.'))}</span>${tag(g.status === 'live' ? '記録中' : formatGame(g))}</div><div class="game-match"><div><span class="muted">${esc(g.teamName)}</span><h3>vs. ${esc(g.opponentName)}</h3></div><strong class="game-score">${a.team.PTS}<span>–</span>${a.opponent}</strong>${icon('chevron')}</div>${resume ? `<div class="resume-line"><span class="live-dot"></span>${esc(g.periods.find(p => p.id === g.currentPeriodId)?.label)} · ${esc(formatGame(g))}<b>試合を再開 ${icon('arrow')}</b></div>` : ''}</a>`;
  return deletable ? `<div class="history-game-card">${card}${action('delete-game', icon('trash'), 'delete-game-button', `data-id="${g.id}" aria-label="${esc(`${g.date} ${g.opponentName}を削除`)}"`)}</div>` : card;
}
const court = `<svg class="court-art" viewBox="0 0 290 220" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width="1.5"><rect x="24" y="15" width="242" height="330" rx="2"/><path d="M24 180h242M24 53c0 136 242 136 242 0M103 15v88h84V15"/><circle cx="145" cy="103" r="42"/><circle cx="145" cy="180" r="28"/><path d="M127 33h36"/><circle cx="145" cy="43" r="10"/></g><circle cx="222" cy="148" r="6" fill="currentColor"/><path d="m186 174 26-18" stroke="currentColor" stroke-width="2" stroke-dasharray="4 5"/></svg>`;
export function homeView(s) {
  const live = s.data.games.filter(g => g.status === 'live').sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  const recent = s.data.games.filter(g => g.status === 'finished').sort((a, b) => b.date.localeCompare(a.date)).slice(0, 3);
  return shell(s, `${heading('YOUR GAME. YOUR RECORD.', 'コートサイドから。')}<section class="hero">${court}<div class="hero-content"><span class="hero-tag">FOCUS ON THE GAME</span><h2>一瞬を、<br>記録に。</h2><p>スタッツ、選手。2タップで完了。<br>目の前のプレーに集中しよう。</p><a class="button hero-button" href="#new">${icon('plus')}試合を記録する${icon('arrow')}</a></div></section><div class="quick-facts"><span>${icon('check')}2タップ入力</span><span>${icon('shield')}端末に自動保存</span><span>${icon('ball')}完全オフライン</span></div>${live.length ? `<section><div class="section-heading"><h2><span class="live-dot"></span>記録中の試合</h2><span class="muted">${live.length} GAMES</span></div><div class="card-list">${live.map(g => gameCard(g, s.data.events, true)).join('')}</div></section>` : ''}<section><div class="section-heading"><h2>最近の試合</h2><a href="#history" class="text-link">すべて見る ${icon('arrow')}</a></div>${recent.length ? `<div class="card-list">${recent.map(g => gameCard(g, s.data.events)).join('')}</div>` : `<div class="empty-state">${icon('history')}<h3>次の試合が、最初の記録。</h3><p>終了した試合とBOX SCOREがここに並びます。</p></div>`}</section>${!s.data.teams.length ? `<a class="setup-card" href="#team/new"><span class="square-icon">${icon('team')}</span><div><h3>まずは、チームを登録</h3><p>背番号と名前を登録して、試合の準備を。</p></div>${icon('chevron')}</a>` : `<a class="setup-card" href="#teams"><span class="square-icon">${icon('team')}</span><div><h3>マイチーム</h3><p>${s.data.teams.length}チーム · 選手を管理</p></div>${icon('chevron')}</a>`}`);
}
export function teamsView(s) {
  return shell(s, `${heading('MY ROSTER', 'チーム', '<a class="button primary small" href="#team/new">＋ 新規登録</a>')}<p class="intro">いつものメンバーを登録して、試合前の準備をスムーズに。</p><div class="card-list">${s.data.teams.map(t => `<a href="#team/${t.id}" class="setup-card"><span class="team-avatar">${esc(t.name.slice(0, 1))}</span><div><h2>${esc(t.name)}</h2><p>${t.players.length} PLAYERS</p></div>${icon('chevron')}</a>`).join('') || '<div class="empty-state"><h3>チームをつくろう</h3><p>背番号と名前だけで、すぐに登録できます。</p><a href="#team/new" class="button primary">チームを登録</a></div>'}</div>`);
}
export function teamFormView(s, draft) {
  return shell(s, `${heading('TEAM SETUP', draft.id ? 'チームを編集' : 'チームを登録')}<form id="team-form"><div class="panel"><label>チーム名<input name="name" maxlength="40" required placeholder="例：TOKYO HOOPS" value="${esc(draft.name)}"></label></div><div class="section-heading"><h2>選手 <span class="muted">${draft.players.length}人</span></h2><span class="draft-status">下書きを自動保存</span></div><div class="roster-editor">${draft.players.map((p, i) => `<div class="roster-edit-row" data-player-id="${esc(p.id)}"><label><span>${i === 0 ? '背番号' : '<span class="sr-only">背番号</span>'}</span><input name="number" aria-label="選手${i + 1}の背番号" inputmode="numeric" pattern="[0-9]{1,3}" maxlength="3" required placeholder="00" value="${esc(p.number)}"></label><label><span>${i === 0 ? '名前' : '<span class="sr-only">名前</span>'}</span><input name="playerName" aria-label="選手${i + 1}の名前" maxlength="40" required placeholder="選手名" value="${esc(p.name)}"></label><button type="button" class="icon-button remove-player" data-action="remove-player" data-id="${esc(p.id)}" aria-label="選手${i + 1}を外す">${icon('close')}</button></div>`).join('')}</div>${action('add-player', `${icon('plus')}選手を追加`, 'button secondary full', 'type="button"')}<p class="help">先発5人は試合作成時に選択できます。登録内容の変更は、過去の試合には影響しません。</p><div class="form-actions"><a href="#teams" class="button secondary">戻る</a><button class="button primary" type="submit">チームを保存 ${icon('check')}</button></div></form>`);
}
export function gameFormView(s, d) {
  if (!s.data.teams.length) return shell(s, `${heading('NEW GAME', '試合の準備')}<div class="empty-state">${icon('team')}<h3>先にチームを登録しましょう</h3><p>選手を登録すると、新しい試合を作成できます。</p><a href="#team/new" class="button primary">チームを登録 ${icon('arrow')}</a></div>`);
  const team = s.data.teams.find(t => t.id === d.teamId) || s.data.teams[0];
  return shell(s, `${heading('NEW GAME', '試合の準備')}<form id="game-form"><div class="panel form-grid"><label>日付<input type="date" name="date" required value="${esc(d.date || localDate())}"></label><label>自チーム<select name="teamId">${s.data.teams.map(t => `<option value="${t.id}" ${t.id === team.id ? 'selected' : ''}>${esc(t.name)}</option>`).join('')}</select></label><label class="span-2">対戦相手<input name="opponentName" maxlength="40" required placeholder="対戦相手のチーム名" value="${esc(d.opponentName)}"></label></div><div class="section-heading"><h2>ゲーム形式</h2></div><div class="panel"><div class="segmented">${[['quarters', '4クォーター'], ['halves', '2ハーフ'], ['custom', '任意設定']].map(([value, label]) => `<label><input type="radio" name="format" value="${value}" ${d.format === value ? 'checked' : ''}><span>${label}</span></label>`).join('')}</div>${d.format === 'custom' ? `<label class="spaced">ピリオド数<input type="number" name="count" min="1" max="12" step="1" required value="${esc(d.count || 4)}"></label>` : ''}<label class="spaced">1ピリオドの時間（分）<input type="number" name="minutes" min="1" max="60" step="0.5" required value="${esc(d.minutes || 8)}"></label><div class="presets">${[5, 6, 7, 8, 10, 12].map(n => action('preset-minutes', `${n}分`, `preset ${Number(d.minutes) === n ? 'active' : ''}`, `type="button" data-value="${n}"`)).join('')}</div><p class="help">時間は試合情報として保存されます。クロック機能はありません。延長は試合中に追加できます。</p></div><div class="section-heading"><h2>出場メンバー</h2><span class="muted">先発は0人または5人</span></div><div class="panel roster-select"><div class="roster-select-head"><span>出場する選手</span><span>先発</span></div>${team.players.map(p => `<div class="roster-select-row"><label class="member-choice"><input type="checkbox" name="participants" value="${p.id}" ${d.participants.includes(p.id) ? 'checked' : ''}><strong>#${esc(p.number)}</strong><span>${esc(p.name)}</span></label><label class="starter-choice"><input type="checkbox" name="starters" value="${p.id}" aria-label="#${esc(p.number)} ${esc(p.name)}を先発にする" ${d.starters.includes(p.id) ? 'checked' : ''}></label></div>`).join('')}</div><p class="help">先発5人を設定すると、コート上の選手を優先表示し、SUBで交代を記録できます。</p><div class="form-actions"><a class="button secondary" href="#home">戻る</a><button type="submit" class="button primary">試合を開始 ${icon('arrow')}</button></div><p class="form-footnote draft-status">入力中の設定も端末に自動保存</p></form>`);
}
export function liveView(s, g, events) {
  const a = aggregate(g, events);
  const period = g.periods.find(p => p.id === g.currentPeriodId);
  const recent = activeEvents(events).slice(-3).reverse();
  return `<main class="live-screen"><header class="live-header"><a href="#home" class="icon-button" aria-label="ホームに戻る">${icon('back')}</a><span class="live-title"><span class="live-dot"></span>LIVE GAME</span><span class="save-state">${icon('check')}保存済み</span>${action('game-menu', icon('more'), 'icon-button', 'aria-label="試合メニュー"')}</header><section class="scoreboard" aria-label="スコア"><div class="score-team"><span class="team-label">MY TEAM</span><strong>${esc(g.teamName)}</strong></div><div class="score-numbers"><b>${a.team.PTS}</b><span>–</span><b>${a.opponent}</b></div><div class="score-team away"><span class="team-label">OPPONENT</span><strong>${esc(g.opponentName)}</strong></div></section><div class="period-row">${action('period-menu', `${esc(period.label)} <span>⌄</span>`, 'period-button', 'aria-label="ピリオド操作"')}<span>${esc(formatGame(g))}</span></div><div class="opponent-row"><span>相手得点</span>${[1, 2, 3].map(n => action('opponent', `+${n}`, 'opponent-button', `data-points="${n}" aria-label="相手に${n}点追加"`)).join('')}</div><div class="input-hint"><span class="step-number">1</span>スタッツを選択<span class="hint-arrow">→</span><span class="muted">2 選手をタップ</span></div><div class="stat-grid">${STAT_DEFS.map(d => action('stat', `<span>${d.label.split(' ')[0]}</span>${d.label.includes(' ') ? `<b class="shot-symbol">${d.tone === 'made' ? '○' : '×'}</b>` : `<small>${d.type === 'OREB' ? 'オフェンスREB' : d.type === 'DREB' ? 'ディフェンスREB' : d.name}</small>`}`, `stat-button ${d.tone}`, `data-type="${d.type}" aria-label="${d.name}"`)).join('')}${action('sub', `<span>SUB</span>${icon('sub')}`, 'stat-button sub', 'aria-label="選手交代"')}</div><section class="recent-events" aria-label="直近の記録"><div class="recent-heading"><span>RECENT PLAYS</span>${action('events', '履歴・編集', 'text-button')}</div><div class="recent-list">${recent.map(e => action('edit-event', `<span>${e.eventType === 'OPP' ? 'OPP' : e.eventType === 'SUB' ? 'SUB' : `#${esc(g.roster.find(p => p.id === e.playerId)?.number)}`}</span><b>${e.eventType === 'OPP' ? `+${e.points}` : e.eventType === 'SUB' ? '交代' : esc(STATS[e.eventType]?.label)}</b>`, 'recent-chip', `data-id="${e.id}" aria-label="${esc(eventLabel(g, e))}を編集"`)).join('') || '<p class="recent-empty">ここに直近3件のプレーを表示</p>'}</div></section><footer class="live-footer">${action('undo', `${icon('undo')}<strong>UNDO</strong><span>直前を取消</span>`, 'undo-button', activeEvents(events).length ? '' : 'disabled')}<a href="#box/${g.id}" class="box-button">${icon('history')}<span>BOX SCORE</span></a></footer></main>`;
}
function shooting(s) {
  return `<div class="shooting-grid">${[['FG', 'FGM', 'FGA'], ['2P', 'P2M', 'P2A'], ['3P', 'P3M', 'P3A'], ['FT', 'FTM', 'FTA']].map(([label, m, a]) => `<div><span>${label}</span><strong>${s[m]}<small>/${s[a]}</small></strong><b>${percent(s[m], s[a])}</b></div>`).join('')}</div>`;
}
export function boxView(s, g, events) {
  const a = aggregate(g, events);
  const label = key => ({ OREB: 'OR', DREB: 'DR', PF: 'F' }[key] || key);
  const row = (p, st, total = false) => `<tr ${total ? 'class="total-row"' : ''}><th scope="row">${total ? 'TEAM' : `<button data-action="player-detail" data-id="${p.id}"><b>#${esc(p.number)}</b><span>${esc(p.name)}</span></button>`}</th>${['PTS', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF'].map(k => `<td ${k === 'PTS' ? 'class="pts-cell"' : ''}>${st[k]}</td>`).join('')}</tr>`;
  const tools = `<div class="heading-actions">${action('share-options', `${icon('share')}共有`, 'button primary small')}${action('csv', `${icon('download')}CSV`, 'button secondary small')}</div>`;
  return shell(s, `${heading('GAME REPORT', 'BOX SCORE', tools)}<div class="report-card"><div class="game-meta"><span>${esc(g.date.replaceAll('-', '.'))} · ${esc(formatGame(g))}</span>${tag(g.status === 'live' ? '記録中' : 'FINAL')}</div><div class="report-score"><div><span>MY TEAM</span><h2>${esc(g.teamName)}</h2></div><strong>${a.team.PTS}<span>–</span>${a.opponent}</strong><div><span>OPPONENT</span><h2>${esc(g.opponentName)}</h2></div></div><div class="period-scores"><div><span>PERIOD</span><b>自チーム</b><b>相手</b></div>${a.periods.map(p => `<div><span>${esc(p.label)}</span><b>${p.home}</b><b>${p.away}</b></div>`).join('')}</div></div><div class="section-heading"><h2>チーム・シューティング</h2></div><div class="panel">${shooting(a.team)}</div><div class="section-heading"><h2>選手スタッツ</h2><span class="muted">選手をタップで詳細</span></div><div class="box-table-wrap"><table class="box-table"><thead><tr><th scope="col">PLAYER</th>${['PTS', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF'].map(k => `<th scope="col">${label(k)}</th>`).join('')}</tr></thead><tbody>${g.roster.map(p => row(p, a.players[p.id])).join('')}${row(null, a.team, true)}</tbody></table></div><div class="rebound-total"><span>OR <b>${a.team.OREB}</b></span><span>DR <b>${a.team.DREB}</b></span><span>REB <b>${a.team.REB}</b></span></div><div class="form-actions">${action('events', `${icon('history')}履歴・編集`)}${g.status === 'live' ? `<a href="#live/${g.id}" class="button primary">記録に戻る ${icon('arrow')}</a>` : action('reopen', '記録を再開', 'button primary')}</div>${g.status === 'live' ? action('finish', '試合を終了する', 'button secondary full spaced') : ''}`);
}
export function playerDetail(g, events, id) {
  const p = g.roster.find(p => p.id === id); const st = aggregate(g, events).players[id];
  return `<div class="player-detail-name"><span class="jersey">${esc(p.number)}</span><h3>${esc(p.name)}</h3><div class="detail-points"><b>${st.PTS}</b> PTS</div></div>${shooting(st)}<div class="detail-stats">${['OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF'].map(k => `<div><span>${({ OREB: 'OR', DREB: 'DR', PF: 'F' }[k] || k)}</span><strong>${st[k]}</strong></div>`).join('')}</div>${action('share-player-image', `${icon('share')}この選手を画像で共有`, 'button primary full', `data-id="${esc(p.id)}"`)}<p class="share-help">iPhoneでは共有先を選択できます。未対応のブラウザではPNGを保存します。</p>`;
}
export function sharedReportView(s, report) {
  const label = key => ({ PF: 'F' }[key] || key);
  const row = (player, stats, total = false) => `<tr ${total ? 'class="total-row"' : ''}><th scope="row">${total ? 'TEAM' : `<button data-action="shared-player-detail" data-id="${esc(player.id)}"><b>#${esc(player.number)}</b><span>${esc(player.name)}</span></button>`}</th>${['PTS', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF'].map(key => `<td ${key === 'PTS' ? 'class="pts-cell"' : ''}>${stats[key]}</td>`).join('')}</tr>`;
  return shell(s, `${heading('PRIVATE REPORT', '共有レポート', tag('閲覧専用'))}<p class="private-report-note">このファイルの内容だけを表示しています。あなたのチーム・試合データには追加されません。</p><div class="report-card"><div class="game-meta"><span>${esc(report.date.replaceAll('-', '.'))} · ${esc(report.format)}</span>${tag(report.status === 'live' ? '記録時点' : 'FINAL')}</div><div class="report-score"><div><span>MY TEAM</span><h2>${esc(report.teamName)}</h2></div><strong>${report.team.PTS}<span>–</span>${report.opponentScore}</strong><div><span>OPPONENT</span><h2>${esc(report.opponentName)}</h2></div></div><div class="period-scores"><div><span>PERIOD</span><b>自チーム</b><b>相手</b></div>${report.periods.map(period => `<div><span>${esc(period.label)}</span><b>${period.home}</b><b>${period.away}</b></div>`).join('')}</div></div><div class="section-heading"><h2>チーム・シューティング</h2></div><div class="panel">${shooting(report.team)}</div><div class="section-heading"><h2>選手スタッツ</h2><span class="muted">選手をタップで詳細</span></div><div class="box-table-wrap"><table class="box-table"><thead><tr><th scope="col">PLAYER</th>${['PTS', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF'].map(key => `<th scope="col">${label(key)}</th>`).join('')}</tr></thead><tbody>${report.players.map(player => row(player, player.stats)).join('')}${row(null, report.team, true)}</tbody></table></div><div class="rebound-total"><span>OR <b>${report.team.OREB}</b></span><span>DR <b>${report.team.DREB}</b></span><span>REB <b>${report.team.REB}</b></span></div><div class="form-actions"><label class="button secondary" for="shared-report-file">別のレポートを開く</label><input type="file" id="shared-report-file" accept=".json,application/json" class="sr-only"><a class="button primary" href="#home">ホームへ</a></div>`);
}
export function sharedPlayerDetail(report, id) {
  const player = report.players.find(candidate => candidate.id === id);
  if (!player) return '<p class="empty-message">選手が見つかりません。</p>';
  const stats = player.stats;
  return `<p class="shared-game-context">${esc(report.teamName)} vs. ${esc(report.opponentName)} · ${esc(report.date.replaceAll('-', '.'))}</p><div class="player-detail-name"><span class="jersey">${esc(player.number)}</span><h3>${esc(player.name)}</h3><div class="detail-points"><b>${stats.PTS}</b> PTS</div></div>${shooting(stats)}<div class="detail-stats">${['OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF'].map(key => `<div><span>${({ OREB: 'OR', DREB: 'DR', PF: 'F' }[key] || key)}</span><strong>${stats[key]}</strong></div>`).join('')}</div>`;
}
export function historyView(s) {
  const games = [...s.data.games].sort((a, b) => b.date.localeCompare(a.date) || b.updatedAt.localeCompare(a.updatedAt));
  return shell(s, `${heading('GAME ARCHIVE', '試合履歴', tag(`${games.length} GAMES`))}<p class="intro">積み重ねたプレーを、いつでも振り返る。</p><div class="card-list">${games.map(g => gameCard(g, s.data.events, false, true)).join('') || '<div class="empty-state"><h3>まだ試合がありません</h3><p>最初の試合を記録してみましょう。</p><a href="#new" class="button primary">試合を記録する</a></div>'}</div>`);
}
export function settingsView(s) {
  const liffId = esc(s.lineShare?.liffId || '');
  const lineStatus = s.lineShare?.liffId ? '設定済み。この端末からLINEカード共有を使えます。' : 'CourtsideのLINEカード共有はあらかじめ有効です。独自のLINEチャネルを使う場合のみLIFF IDを変更してください。';
  return shell(s, `${heading('PREFERENCES', '設定とデータ')}<section class="panel settings-panel"><h2>入力・表示</h2><label class="setting-row"><span><strong>連続入力</strong><small>2P・3Pの後にAST / OR・DRを提案</small></span><input type="checkbox" role="switch" id="continuous" ${s.preferences.continuous ? 'checked' : ''}></label><label class="setting-row"><span><strong>外観</strong><small>見やすい明るさを選択</small></span><select id="theme" aria-label="外観">${[['system', '端末に合わせる'], ['light', 'ライト'], ['dark', 'ダーク']].map(([v, label]) => `<option value="${v}" ${s.preferences.theme === v ? 'selected' : ''}>${label}</option>`).join('')}</select></label></section><section class="panel settings-panel"><h2>LINEカード共有</h2><p class="help">LINEのトークへ、試合結果カードと「BOX SCOREを見る」ボタンを送ります。このCourtsideではすぐ利用できます。独自のLINE Developersチャネルを使う場合のみLIFF IDを保存してください。</p><form id="line-share-form"><label>LIFF ID<input id="line-liff-id" name="liffId" value="${liffId}" maxlength="101" autocapitalize="off" autocomplete="off" spellcheck="false" placeholder="1234567890-AbCdEfgh"></label><button class="button primary full spaced" type="submit">LINEカード共有を保存</button></form><p class="help">${lineStatus}</p></section><section class="panel settings-panel"><h2>受け取った共有レポート</h2><p class="help">共有された1試合のファイルを、データへ取り込まず読み取り専用で開きます。</p><label class="button primary full" for="shared-report-file">${icon('share')}共有レポートを開く</label><input type="file" id="shared-report-file" accept=".json,application/json" class="sr-only"></section><section class="panel settings-panel"><h2>バックアップ</h2><p class="help">試合・チーム・設定を1つのJSONに保存します。定期的に「ファイル」などへ書き出してください。</p>${action('export-json', `${icon('download')}全データを書き出す`, 'button primary full')}<label class="button secondary full spaced" for="restore-file">JSONから復元</label><input type="file" id="restore-file" accept=".json,application/json" class="sr-only"><p class="help">復元前に内容を検証し、件数を表示します。復元すると現在の全データが置き換わります。</p></section><section class="panel settings-panel"><h2>この端末の保存状態</h2><div class="storage-status">${statusChip(s)}<span>${s.data.teams.length}チーム / ${s.data.games.length}試合 / ${activeEvents(s.data.events).length}記録</span></div><p class="help">${s.pwa.error ? esc(s.pwa.error) : s.pwa.ready ? 'アプリ本体のキャッシュが完了しました。通信がなくても利用できます。' : '初回のキャッシュ完了までオンラインでお待ちください。'}</p>${s.pwa.update ? '<p class="notice">更新があります。Courtsideの画面をすべて閉じて開き直すと適用されます。</p>' : ''}${action('persist', '保存領域の保持をリクエスト', 'button secondary full')}<p class="help" id="persist-status">ブラウザのデータ削除や端末の故障に備え、JSONバックアップもご利用ください。</p></section><section class="panel settings-panel"><h2>iPhoneのホーム画面に追加</h2><ol class="install-steps"><li>Safariでこのアプリを開く</li><li>共有メニューから「ホーム画面に追加」</li><li>表示される場合は「Webアプリとして開く」をONにし、追加</li><li>追加したアプリを起動し、「オフライン利用OK」を確認</li></ol></section><p class="version-note">COURTSIDE 1.0.16 · BUILT FOR THE SIDELINES</p>`);
}
export function pickerHTML(g, events, type, options = {}) {
  const on = lineup(g, events); const tracked = g.starters.length === 5 && !options.plain;
  const players = (options.players || g.roster).filter(p => p.id !== options.exclude && (!options.only || options.only.includes(p.id)));
  const group = (list, label) => list.length ? `<p class="picker-label">${label}</p><div class="player-grid">${list.map(p => action(options.action || 'pick-player', `<strong>#${esc(p.number)}</strong><span>${esc(p.name)}</span>`, 'player-button', `data-id="${p.id}"`)).join('')}</div>` : '';
  return `<p class="picker-instruction">${esc(options.instruction || '記録する選手をタップ')}</p>${group(tracked ? players.filter(p => on.includes(p.id)) : players, tracked ? 'ON COURT' : 'PLAYERS')}${tracked ? `<details ${options.only || options.showBench ? 'open' : ''} class="bench-list"><summary>ベンチの選手を表示</summary>${group(players.filter(p => !on.includes(p.id)), 'BENCH')}</details>` : ''}`;
}
export function eventsHTML(g, events) {
  const active = activeEvents(events).reverse();
  return `<p class="help">タップして選手・項目・ピリオドを修正、または個別削除できます。</p><div class="event-list">${active.map(e => action('edit-event', `<span class="event-period">${esc(g.periods.find(p => p.id === e.periodId)?.label)}</span><span>${esc(eventLabel(g, e))}</span>${icon('chevron')}`, 'event-row', `data-id="${e.id}"`)).join('') || '<p class="empty-message">まだ記録がありません。</p>'}</div>`;
}
export function editEventHTML(g, e) {
  return `<form id="event-form" data-id="${e.id}"><p class="help">${esc(eventLabel(g, e))}</p><label>ピリオド<select name="periodId">${g.periods.map(p => `<option value="${p.id}" ${p.id === e.periodId ? 'selected' : ''}>${esc(p.label)}</option>`).join('')}</select></label>${e.eventType === 'SUB' ? '<p class="notice">交代の選手を変更する場合は、この記録を削除して再入力してください。</p>' : e.eventType === 'OPP' ? `<label class="spaced">相手得点<select name="points">${[1, 2, 3].map(n => `<option ${e.points === n ? 'selected' : ''}>${n}</option>`).join('')}</select></label>` : `<label class="spaced">スタッツ<select name="eventType">${STAT_DEFS.map(d => `<option value="${d.type}" ${e.eventType === d.type ? 'selected' : ''}>${d.label} · ${d.name}</option>`).join('')}</select></label><label class="spaced">選手<select name="playerId">${g.roster.map(p => `<option value="${p.id}" ${p.id === e.playerId ? 'selected' : ''}>#${esc(p.number)} ${esc(p.name)}</option>`).join('')}</select></label>`}<button type="submit" class="button primary full spaced">変更を保存</button>${action('delete-event', 'この記録を削除', 'button danger full spaced', `type="button" data-id="${e.id}"`)}</form>`;
}
